version: '3'

services:

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - 5432:5432

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: mydatabase
    ports:
      - 3306:3306

  nginx:
    build: .
    ports:
      - 80:80

  apache:
    image: httpd:latest
    ports:
      - 81:80
